defaultRules:
  create: true
  rules:
    etcd: false
    kubeScheduler: false

kubeScheduler:
  enabled: false

kubeEtcd:
  enabled: false

alertmanager:
  enabled: true

grafana:
  enabled: true
  adminPassword: prom-operator

prometheusOperator:
  enabled: true

prometheus:
  enabled: true

  additionalServiceMonitors:
    - name: "emojivoto-monitor"
      selector:
        matchExpressions:
          - key: app
            operator: In
            values:
              - emoji-svc
              - voting-svc
      namespaceSelector:
        matchNames: 
          - emojivoto
      endpoints:
        - port: "prom"

